### ISSUE TITLE
在docker中遇到跨域问题，图片加载不出来。

### ISSUE THREAD

**Issue by zolagz** [IITII/pic_online#2]
vendor.aceed81b.js:62 Uncaught (in promise) Error: Image failed to load!And failed src was: http://localhost:80/images/0001.png
    at vendor.aceed81b.js:62:75741
    at Z._log (vendor.aceed81b.js:62:76377)
    at vendor.aceed81b.js:62:75724

请问，是把该项目下载后，注释 node_modules/vue-waterfall-plugin-next/dist/my-lib.es.js:340 行吗？我尝试这么做，好像还是不行。

**Comment by IITII** [comment]
注释后需要重新构建。推荐使用 nginx 做统一，都弄到一个 host:port 下面就可以了。

~上游更新了，我看看端午有没有空修一下~

**Comment by zolagz** [comment]
好的。大佬可以搞一个注释后在打包的版本发布出来吗？

**Comment by zolagz** [comment]
大佬，是否可以考虑，直接把上游的跨域，在该项目中禁用了呢?

**Comment by IITII** [comment]
你试试最新的 release #v3.2.0

**Comment by zolagz** [comment]
最新的 release #v3.2.0在docker中使用还是同样的问题：vendor.aceed81b.js:62 Uncaught (in promise) Error: Image failed to load!And failed

**Comment by IITII** [comment]
wget https://raw.githubusercontent.com/IITII/pic_online_backend/main/docker-compose.yml
docker-compose up -d
用这个试试
